apiVersion: v1
kind: Pod
metadata:
  name: s3-client
  namespace: default
spec:
  automountServiceAccountToken: false
  containers:
    - name: aws
      image: docker.io/amazon/aws-cli
      command: ["sleep", "infinity"]
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: garage-secrets
              key: GARAGE_DEFAULT_ACCESS_KEY
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: garage-secrets
              key: GARAGE_DEFAULT_SECRET_KEY
        - name: AWS_DEFAULT_REGION
          value: garage
        - name: AWS_ENDPOINT_URL
          value: http://garage:3900

